### ISSUE TITLE
HasParent() circular reference only checks on level deep.

### ISSUE THREAD

**Issue by brendesp** [euroteltr/rbac#1]
*Role.AddParent() checks for circular refrences, but only checks one level deep.  It needs to check the whole tree.

It looks like the problem is HasParent only looks one level deep.  Fixing HasParent() should Fix AddParent()

**Comment by brendesp** [comment]
I have a fix I can upload, but got permission denied.

**Comment by brendesp** [comment]
''' go
// HasParent checks if a role is in parent roles
func (r *Role) HasParent(parentID string) bool {
	ok := hasParentDeep(r, parentID)
	return ok
}

// hasParentDeep check the parent tree for the parentID
func hasParentDeep(child *Role, parentID string) bool {
	if _, ok := child.parents.Load(parentID); ok {
		return ok
	}
	found := false
	child.parents.Range(func(key, value interface{}) bool {
		found = hasParentDeep(value.(*Role), parentID)
		if found {
			// returning false breaks out of Range call.
			return false
		}
		return true
	})
	return found
}
'''

**Comment by derkan** [comment]
Thanks for patch. Please;

- Clone this repo
- Make your changes on your clone
- Make pull request. 

I'll check and apply then.

**Comment by brendesp** [comment]
Thanks.  Can you create a new release so I can add it to my go module.

**Comment by derkan** [comment]
OK, done.
